### ISSUE TITLE
Karte bewegt sich mit

### ISSUE THREAD

**Issue by jkim1708** [br-data/corona-deutschland-karte#61]
Beim Verstellen des Zeitpunktes bewegt sich die Karte mit.

**Comment by MichaelKreil** [comment]
Ups, den Bug kannte ich noch nicht. Kann ihn aber auch nicht reproduzieren.
Welcher Browser/welches Gerät?

**Comment by jkim1708** [comment]
Komisch, die Karte sieht ganz anders aus als gestern. Muss wohl geträumt haben - sorry

**Comment by MichaelKreil** [comment]
:)  Happens.
Aber Danke, dass du dir generell die Mühe machst.
