### ISSUE TITLE
Ortsnamen werden nicht angezeigt

### ISSUE THREAD

**Issue by jkim1708** [br-data/corona-deutschland-karte#62]
Auch nach Näherzoomen werden die Ortsnamen nicht angezeigt

**Comment by MichaelKreil** [comment]
Die Ortsnamen können aus Platzgründen nicht angezeigt werden.
Nur wenn man einen Landkreis/eine Stadt auswählt/darüber hovert, wird der Name angezeigt.
Gibt es eine andere Idee?

**Comment by jkim1708** [comment]
Auch hier - die Karte sieht anders aus. Habe auch keinen anderen Browser verwendet.
