### ISSUE TITLE
unable to run /bin/2_prepare_data.js

### ISSUE THREAD

**Issue by tr4ssh-un1** [br-data/corona-deutschland-karte#63]
`(node:22087) UnhandledPromiseRejectionWarning: Error
    at data.forEach.entry (/home/userubuntu/corona/corona-deutschland-karte/bin/2_prepare_data.js:157:37)
    at Array.forEach (<anonymous>)
    at /home/userubuntu/corona/corona-deutschland-karte/bin/2_prepare_data.js:149:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22087) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22087) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Letzte Woche konnte ich noch 1_fetch_data.js & 2_prepare_data.js ausführen. Seit dem 03.12. scheint dies nichtmehr zu funktionieren, da er in der forEach in Zeile 149 bzw. Zeile 157 das Error(); wirft aber es nirgendwo gecatched wird. Kenne mich leider mit node.js nicht gut aus.

**Comment by MichaelKreil** [comment]
sorry, jetzt erst zeit gefunden :/ 
Klingt komisch. Kann ich nicht reproduzieren.
Kannst du mal frisch clonen und neu builden etc.?

**Comment by MichaelKreil** [comment]
no response
